
version: "3.8"
services:
  chat_app:
    image: jacjamg/homework_02:latest
    build: .
    container_name: chat_app_2
    ports:
      - "80:3000"
    environment:
      - PORT=3000
    volumes:
      - ./:/app
    command: ["node", "index.js"]
   


